`kaocha` prints hints, when `secrets.env` is missing

diff --git a/kaocha b/kaocha
--- a/kaocha
+++ b/kaocha
@@ -1,4 +1,12 @@
 #!/usr/bin/env bash
 
-. secrets.env
-clojure -J-Xmx512m -M:dev:test --config-file tests.edn "$@"
+set -euo pipefail # stop, when error occurs, even within pipes
+
+function help:secrets-missing() {
+  echo "secrets.env not found!"
+  echo "Try:"
+  echo "  cp example-secrets.env secrets.env"
+}
+
+[ -f secrets.env ] && . secrets.env || (help:secrets-missing >&2 && exit 1)
+clojure -J-Xmx512m -M:dev:test "$@"
